### ISSUE TITLE
pytorch version

### ISSUE THREAD

**Issue by ilovedoudou** [textflint/textflint#7]
hi，which version of pytorch does it need？

**Comment by anaivebird** [comment]
It seem that no explicit restriction on pytorch version, since the pytorch API we called is stable on main-stream pytorch version. Latest version of pytorch will work.

Of course, it will be a good choice to use `pip install -r requirements.txt` to install dependencies. Also, if you install TextFlint by `pip install textflint`, pip will install all dependencies automatically for you.
